"""empty message

Revision ID: 187972d86703
Revises: fe8bb8a8df57
Create Date: 2025-04-13 16:57:43.168053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '187972d86703'
down_revision = 'fe8bb8a8df57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('post_media_id_fkey', type_='foreignkey')
        batch_op.drop_column('media_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('post_media_id_fkey', 'media', ['media_id'], ['id'])

    # ### end Alembic commands ###
