"""empty message

Revision ID: 583e86901557
Revises: 0ecc938bcc92
Create Date: 2025-04-13 16:40:23.074975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '583e86901557'
down_revision = '0ecc938bcc92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['comment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('comment_id')

    # ### end Alembic commands ###
